# Generated by Django 6.1.1 on 2026-10-01 01:04

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import recuperacion.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaObjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('icono', models.CharField(default='fa-box', help_text='Clase FontAwesome o emoji de representación (ej: 🔑, 📱, 🧥)', max_length=40)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Categoría de Objeto',
                'verbose_name_plural': 'Categorías de Objetos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Coincidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_similitud', models.FloatField(help_text='Puntaje de afinidad calculado entre 0% y 100%')),
                ('criterios_match', models.TextField(blank=True, help_text='Detalle estructurado de factores coincidentes (categoría, color, lugar, fechas)')),
                ('estado', models.CharField(choices=[('sugerida', 'Coincidencia Sugerida por Sistema'), ('en_verificacion', 'En Verificación con Conserjería'), ('confirmada', 'Confirmada por Propietario'), ('descartada', 'Descartada / Falso Positivo'), ('resuelta', 'Resuelta / Objeto Entregado')], default='sugerida', max_length=25)),
                ('fecha_coincidencia', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Coincidencia de Objetos',
                'verbose_name_plural': 'Coincidencias de Objetos',
                'ordering': ['-porcentaje_similitud', '-fecha_coincidencia'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('residente', 'Residente / Ciudadano'), ('conserje', 'Encargado de Recinto / Conserje'), ('admin', 'Administrador del Edificio')], default='residente', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=25, null=True)),
                ('departamento_torre', models.CharField(blank=True, help_text='Ejemplo: Torre A - Depto 502 / Oficina 301', max_length=80, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MensajeChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('coincidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='recuperacion.coincidencia')),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensaje de Coordinación',
                'verbose_name_plural': 'Mensajes de Coordinación',
                'ordering': ['fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
                ('url_destino', models.CharField(blank=True, default='', max_length=255)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_seguimiento', models.CharField(default=recuperacion.models.generar_codigo_seguimiento, max_length=20, unique=True)),
                ('tipo_registro', models.CharField(choices=[('perdido', 'Objeto Perdido (Reportado por Dueño)'), ('encontrado', 'Objeto Encontrado (En Custodia o Reportado por Vecino)')], max_length=20)),
                ('subcategoria', models.CharField(help_text='Ejemplo: Control Remoto Portón, Audífonos Sony, Tarjeta bip', max_length=100)),
                ('color_principal', models.CharField(help_text='Ejemplo: Negro, Azul marino, Plateado, Rojo', max_length=50)),
                ('marca', models.CharField(blank=True, default='', max_length=80)),
                ('ubicacion_bodega', models.CharField(blank=True, default='', help_text='Casillero, locker o estante físico en recepción (solo para objetos encontrados)', max_length=100)),
                ('descripcion_publica', models.TextField(help_text='Detalles generales visibles para la búsqueda sin exponer información crítica')),
                ('clave_verificacion_privada', models.TextField(help_text='Detalle exclusivo e invisible públicamente para validar pertenencia (ej: stickers, roturas internas, número serial)')),
                ('fecha_suceso', models.DateField(help_text='Fecha aproximada en que se perdió o se encontró el objeto')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('registrado', 'Registrado (En Búsqueda / En Custodia)'), ('en_verificacion', 'En Verificación (Proceso de Cotejo)'), ('entregado', 'Entregado al Propietario'), ('dado_de_baja', 'Dado de Baja / Descartado')], default='registrado', max_length=25)),
                ('token_retiro', models.CharField(default=recuperacion.models.generar_token_retiro, help_text='Código numérico de 6 dígitos para retiro seguro en mesón', max_length=6)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('observaciones_entrega', models.TextField(blank=True, default='')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recuperacion.categoriaobjeto')),
                ('entregado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetos_recibidos', to=settings.AUTH_USER_MODEL)),
                ('entregado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetos_entregados_por', to=settings.AUTH_USER_MODEL)),
                ('usuario_reporta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetos_reportados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Objeto',
                'verbose_name_plural': 'Objetos',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('datos_falsos', 'Datos incorrectos o falsos en publicación'), ('entrega_irregular', 'Inconveniente o sospecha en entrega física'), ('mal_uso', 'Mal uso de la plataforma'), ('otro', 'Otro asunto')], max_length=30)),
                ('descripcion', models.TextField()),
                ('resuelta', models.BooleanField(default=False)),
                ('respuesta_admin', models.TextField(blank=True, default='')),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias_reportadas', to=settings.AUTH_USER_MODEL)),
                ('objeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias', to='recuperacion.objeto')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'ordering': ['-fecha_reporte'],
            },
        ),
        migrations.AddField(
            model_name='coincidencia',
            name='objeto_encontrado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coincidencias_como_encontrado', to='recuperacion.objeto'),
        ),
        migrations.AddField(
            model_name='coincidencia',
            name='objeto_perdido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coincidencias_como_perdido', to='recuperacion.objeto'),
        ),
        migrations.CreateModel(
            name='Recinto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('area_comun', 'Área Común / Tránsito'), ('punto_custodia', 'Punto de Custodia / Bodega / Conserjería')], default='area_comun', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recintos_a_cargo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recinto o Ubicación',
                'verbose_name_plural': 'Recintos y Ubicaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='objeto',
            name='ubicacion',
            field=models.ForeignKey(help_text='Área o sector del edificio donde ocurrió el hallazgo o extravío', on_delete=django.db.models.deletion.PROTECT, related_name='objetos_registrados', to='recuperacion.recinto'),
        ),
        migrations.AlterUniqueTogether(
            name='coincidencia',
            unique_together={('objeto_perdido', 'objeto_encontrado')},
        ),
    ]
