# Generated by Django 6.1.1 on 2026-10-01 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recuperacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto',
            name='contacto_email',
            field=models.EmailField(blank=True, default='', help_text='Correo electrónico de contacto para avisos', max_length=254),
        ),
        migrations.AddField(
            model_name='objeto',
            name='contacto_nombre',
            field=models.CharField(blank=True, default='', help_text='Nombre completo de contacto para reportes de invitados', max_length=120),
        ),
        migrations.AddField(
            model_name='objeto',
            name='contacto_telefono',
            field=models.CharField(blank=True, default='', help_text='Teléfono o WhatsApp de contacto', max_length=30),
        ),
        migrations.AddField(
            model_name='objeto',
            name='es_invitado',
            field=models.BooleanField(default=False, help_text='Indica si el reporte fue registrado por un visitante o usuario no autenticado'),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='usuario_reporta',
            field=models.ForeignKey(blank=True, help_text='Usuario registrado que reporta (null si es reporte de invitado/visitante)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetos_reportados', to=settings.AUTH_USER_MODEL),
        ),
    ]
